import React, { useState } from 'react';
import FooterColumn from './FooterColumn';
import { Globe, Facebook, Twitter, Instagram, ChevronDown } from 'lucide-react';

const Footer = () => {
    const [activeTab, setActiveTab] = useState('Popular');
    const [isExpanded, setIsExpanded] = useState(false);

    const tabs = [
        'Popular',
        'Arts & culture',
        'Beach',
        'Mountains',
        'Outdoors',
        'Things to do'
    ];

    const inspirationData = {
        'Popular': [
            // Initial 17 items (rows 1-3 partially)
            { city: 'Charlotte', type: 'Holiday rentals' },
            { city: 'Kyoto', type: 'Villa rentals' },
            { city: 'Charleston', type: 'Flat rentals' },
            { city: 'Gulf Shores', type: 'Monthly Rentals' },
            { city: 'Oahu', type: 'Monthly Rentals' },
            { city: 'Detroit', type: 'Flat rentals' },
            { city: 'Albuquerque', type: 'Holiday rentals' },
            { city: 'Barcelona', type: 'House rentals' },
            { city: 'Montreal', type: 'Holiday rentals' },
            { city: 'St. Petersburg', type: 'Monthly Rentals' },
            { city: 'San Diego', type: 'Cabin rentals' },
            { city: 'San Juan', type: 'Flat rentals' },
            { city: 'Madrid', type: 'Monthly Rentals' },
            { city: 'Amsterdam', type: 'Apartment rentals' },
            { city: 'London', type: 'Flat rentals' },
            { city: 'Wilmington', type: 'Cottage rentals' },
            { city: 'Key West', type: 'Cottage rentals' },
            // Expanded items
            { city: 'Memphis', type: 'Flat rentals' },
            { city: 'Philadelphia', type: 'Holiday rentals' },
            { city: 'Orange Beach', type: 'House rentals' },
            { city: 'Cleveland', type: 'House rentals' },
            { city: 'Kauai', type: 'Flat rentals' },
            { city: 'San Antonio', type: 'Apartment rentals' },
            { city: 'Brooklyn', type: 'Apartment rentals' },
            { city: 'Daytona Beach', type: 'Apartment rentals' },
            { city: 'Athens', type: 'Holiday rentals' },
            { city: 'Santo Domingo', type: 'Holiday rentals' },
            { city: 'Tokyo', type: 'House rentals' },
            { city: 'Dubai', type: 'Holiday rentals' },
            { city: 'Milan', type: 'Flat rentals' },
            { city: 'West Palm Beach', type: 'Flat rentals' },
            { city: 'Dallas', type: 'Holiday rentals' },
            { city: 'Galveston', type: 'Villa rentals' },
            { city: 'Pittsburgh', type: 'Monthly Rentals' },
            { city: 'Portland', type: 'Flat rentals' },
            { city: 'Minneapolis', type: 'House rentals' },
            { city: 'Raleigh', type: 'Apartment rentals' },
            { city: 'Maui', type: 'Apartment rentals' },
            { city: 'Pocono Mountains', type: 'Holiday rentals' },
            { city: 'Osaka', type: 'Monthly Rentals' },
            { city: 'Sarasota', type: 'Apartment rentals' },
            { city: 'Branson', type: 'Apartment rentals' },
            { city: 'Nashville', type: 'Apartment rentals' },
            { city: 'Washington', type: 'Holiday rentals' },
            { city: 'Destin', type: 'Flat rentals' },
            { city: 'Florida Keys', type: 'Apartment rentals' },
            { city: 'Chicago', type: 'Flat rentals' },
            { city: 'Sacramento', type: 'Villa rentals' },
            { city: 'Fort Lauderdale', type: 'Flat rentals' },
            { city: 'Las Vegas', type: 'Flat rentals' },
            { city: 'Cape Cod', type: 'Cottage rentals' },
            { city: 'Cartagena', type: 'Monthly Rentals' },
            { city: 'Medellín', type: 'Villa rentals' },
            { city: 'Dublin', type: 'Apartment rentals' },
            { city: 'Savannah', type: 'House rentals' },
            { city: 'Manhattan', type: 'Apartment rentals' },
            { city: 'Kansas City', type: 'Holiday rentals' },
            { city: 'St. Augustine', type: 'Cottage rentals' },
            { city: 'Santa Barbara', type: 'Apartment rentals' },
            { city: 'Clearwater', type: 'Villa rentals' },
            { city: 'Outer Banks', type: 'Cottage rentals' },
            { city: 'Honolulu', type: 'Apartment rentals' },
            { city: 'Mexico City', type: 'Flat rentals' },
            { city: 'Anaheim', type: 'Apartment rentals' },
            { city: 'Columbus', type: 'Flat rentals' },
            { city: 'Fort Worth', type: 'Monthly Rentals' },
            { city: 'Porto', type: 'Holiday rentals' },
            { city: 'Corpus Christi', type: 'Villa rentals' },
            { city: 'Santa Fe', type: 'Monthly Rentals' },
            { city: 'Salt Lake City', type: 'Cottage rentals' },
            { city: 'Sedona', type: 'Monthly Rentals' },
            { city: 'Puerto Vallarta', type: 'Holiday rentals' },
            { city: 'Miami Beach', type: 'Holiday rentals' },
            { city: 'New Orleans', type: 'Flat rentals' },
            { city: 'Tampa', type: 'Holiday rentals' },
            { city: 'New York City', type: 'Flat rentals' },
            { city: 'Venice', type: 'Villa rentals' },
            { city: 'Oklahoma City', type: 'Flat rentals' },
            { city: 'Cincinnati', type: 'Holiday rentals' },
            { city: 'Atlanta', type: 'Apartment rentals' },
            { city: 'Rome', type: 'Monthly Rentals' },
            { city: 'Los Angeles', type: 'House rentals' },
            { city: 'Hollywood', type: 'Apartment rentals' },
            { city: 'South Lake Tahoe', type: 'Flat rentals' },
            { city: 'Orlando', type: 'Monthly Rentals' },
            { city: 'Boston', type: 'House rentals' },
            { city: 'Indianapolis', type: 'House rentals' },
            { city: 'Houston', type: 'Monthly Rentals' },
            { city: 'Cape Coral', type: 'Monthly Rentals' },
            { city: 'Kissimmee', type: 'Flat rentals' },
            { city: 'Miami', type: 'House rentals' },
            { city: 'Cancún', type: 'House rentals' },
            { city: 'St. Louis', type: 'Holiday rentals' },
            { city: 'Myrtle Beach', type: 'Monthly Rentals' },
            { city: 'Ocean City', type: 'Holiday rentals' },
            { city: 'Chattanooga', type: 'Cottage rentals' },
            { city: 'Breckenridge', type: 'Villa rentals' },
            { city: 'Bangkok', type: 'Villa rentals' },
            { city: 'Louisville', type: 'Monthly Rentals' },
        ],
        'Arts & culture': [
            { city: 'Lake Como', type: 'House rentals' },
            { city: 'Haeundae Beach', type: 'House rentals' },
            { city: 'Cuyahoga Valley National Park', type: 'House rentals' },
            { city: 'Times Square', type: 'Apartment rentals' },
            { city: 'Assateague Island', type: 'Apartment rentals' },
            { city: 'Olympic National Park', type: 'Holiday rentals' },
            { city: 'SoFi Stadium', type: 'Holiday rentals' },
            { city: 'Lambeau Field', type: 'Holiday rentals' },
            { city: 'Canal Saint-Martin', type: 'Flat rentals' },
            { city: 'Holiday Valley Ski Resort', type: 'House rentals' },
            { city: 'Tower Bridge', type: 'Flat rentals' },
            { city: 'Paris', type: 'House rentals' },
            // Expanded List from Image
            { city: 'Snowbird Ski Resort', type: 'Apartment rentals' },
            { city: 'Coronado Islands', type: 'House rentals' },
            { city: 'Las Croabas', type: 'House rentals' },
            { city: 'Camelback Mountain Resort', type: 'Holiday rentals' },
            { city: 'Sugarbush Resort', type: 'Flat rentals' },
            { city: 'Belleayre Mountain Ski Center', type: 'Holiday rentals' },
            { city: 'Jay Peak Resort', type: 'House rentals' },
            { city: 'Samara Beach', type: 'Apartment rentals' },
            { city: 'Cerritos Beach', type: 'Holiday rentals' },
            { city: 'Granby Ranch', type: 'Flat rentals' },
            { city: 'Red Hook', type: 'Apartment rentals' },
            { city: 'Schweitzer Mountain Resort', type: 'Apartment rentals' },
            { city: 'Phoenix Convention Center', type: 'Holiday rentals' },
            { city: 'Santa Teresa', type: 'Villa rentals' },
            { city: 'National Harbor', type: 'House rentals' },
            { city: 'Everglades', type: 'Cottage rentals' },
            { city: 'Kirkwood Mountain Resort', type: 'Cabin rentals' },
            { city: 'Lucas Oil Stadium', type: 'Holiday rentals' },
            { city: 'Playa Potrero, Costa Rica', type: 'Holiday rentals' },
            { city: 'Campo de\' Fiori', type: 'Apartment rentals' },
            { city: 'Jack Frost Ski Resort', type: 'Holiday rentals' },
            { city: 'Lake Tahoe', type: 'House rentals' },
            { city: 'Nāpili Bay', type: 'Flat rentals' },
            { city: 'Martha\'s Vineyard', type: 'Holiday rentals' },
            { city: 'Beech Mountain Ski Resort', type: 'Holiday rentals' },
            { city: 'Los Angeles Convention Center', type: 'Apartment rentals' },
            { city: 'Ruby Falls', type: 'House rentals' },
            { city: 'North Cascades National Park', type: 'House rentals' },
            { city: 'Amalfi Coast', type: 'Villa rentals' },
            { city: 'Flathead Lake', type: 'Cabin rentals' },
            { city: 'Snowmass Ski Resort', type: 'Flat rentals' },
            { city: 'Captiva Island', type: 'Apartment rentals' },
            { city: 'New River Gorge National Park and Preserve', type: 'Flat rentals' },
            { city: 'Orange County Convention Center', type: 'Villa rentals' },
            { city: 'River Street', type: 'Flat rentals' },
            { city: 'Breckenridge Ski Resort', type: 'Apartment rentals' },
            { city: 'Jiminy Peak Mountain Resort', type: 'Holiday rentals' },
            { city: 'Loon Mountain Resort', type: 'Holiday rentals' },
            { city: 'Big Boulder Mountain', type: 'Holiday rentals' },
            { city: 'The Galleria', type: 'Flat rentals' },
            { city: 'Isla Holbox', type: 'Holiday rentals' },
            { city: 'Indiana Dunes National Park', type: 'Cabin rentals' },
            { city: 'Shinjuku Sta.', type: 'House rentals' },
            { city: 'Hocking Hills State Park', type: 'Holiday rentals' },
            { city: 'Miami Beach Convention Center', type: 'Apartment rentals' },
            { city: 'Anna Maria Island', type: 'Holiday rentals' },
            { city: 'Vanderbilt University', type: 'Holiday rentals' },
            { city: 'Everglades National Park', type: 'Holiday rentals' },
            { city: 'Sequoia National Park', type: 'Cabin rentals' },
            { city: 'Ilha Grande', type: 'House rentals' },
            { city: 'Seattle', type: 'House rentals' },
            { city: 'Salt Palace Convention Center', type: 'Holiday rentals' },
            { city: 'Music Row', type: 'Holiday rentals' },
            { city: 'Jaco Beach', type: 'Flat rentals' },
            { city: 'San Francisco', type: 'Holiday rentals' },
            { city: 'Sunday River Resort', type: 'Apartment rentals' },
            { city: 'Bukchon Hanok Village', type: 'Flat rentals' },
            { city: 'Val Thorens', type: 'Apartment rentals' },
            { city: 'Tamarindo Beach Costa Rica', type: 'Villa rentals' },
            { city: 'Hampstead Heath', type: 'Holiday rentals' },
            { city: 'Cozumel', type: 'Apartment rentals' },
            { city: 'Hongdae Street', type: 'Holiday rentals' },
            { city: 'Lake Lucerne', type: 'Apartment rentals' },
            { city: 'Santa Catalina Island', type: 'Villa rentals' },
            { city: 'Mountain Creek Resort', type: 'Apartment rentals' },
            { city: 'Great Smoky Mountains', type: 'Villa rentals' },
            { city: 'Kia Center', type: 'House rentals' },
            { city: 'Hard Rock Stadium', type: 'Holiday rentals' },
            { city: 'Okemo Mountain Resort', type: 'Flat rentals' },
            { city: 'Hvar', type: 'Villa rentals' },
            { city: 'Paradise Island', type: 'Villa rentals' },
            { city: 'Rockefeller Center', type: 'Flat rentals' },
            { city: 'Singer Island', type: 'Flat rentals' },
            { city: 'Las Vegas Strip', type: 'House rentals' },
            { city: 'Lake Wallenpaupack', type: 'Flat rentals' },
            { city: 'Zona T', type: 'Holiday rentals' },
            { city: 'Shenandoah National Park', type: 'House rentals' },
            { city: 'Boyne Mountain Resort', type: 'Villa rentals' },
            { city: 'Playas del Coco', type: 'Apartment rentals' },
            { city: 'Lake Garda', type: 'House rentals' },
            { city: 'Indian Lake Ohio', type: 'Holiday rentals' },
            { city: 'Cebu IT Park', type: 'House rentals' },
            { city: 'Lake Gregory', type: 'Cabin rentals' },
            { city: 'Mount Snow', type: 'Apartment rentals' },
            { city: 'Northstar California Resort', type: 'Flat rentals' },
            { city: 'Lake Crescent', type: 'Cottage rentals' },
        ],
        'Beach': [
            { city: 'Playa Conchal', type: 'Villa rentals' },
            { city: 'Playa Negra', type: 'Villa rentals' },
            { city: 'Cabo San Lucas', type: 'House rentals' },
            { city: 'Turtle Beach', type: 'Apartment rentals' },
            { city: 'Caye Caulker', type: 'House rentals' },
            { city: 'Bridgetown', type: 'House rentals' },
            { city: 'Pattaya Beach', type: 'House rentals' },
            { city: 'Bingin Beach', type: 'Holiday rentals' },
            { city: 'Coxen Hole', type: 'Holiday rentals' },
            { city: 'Pacific Beach', type: 'Apartment rentals' },
            { city: 'Armacao dos Buzios', type: 'Apartment rentals' },
            { city: 'Simpson Bay', type: 'Beachfront rentals' },
            // Expanded items from image
            { city: 'El Medano Beach', type: 'Villa rentals' },
            { city: 'Playa Sayulita', type: 'Pet-friendly rentals' },
            { city: 'Sarasota Beach', type: 'Flat rentals' },
            { city: 'Wrightsville Beach, NC', type: 'Apartment rentals' },
            { city: 'Whitecap Beach', type: 'Apartment rentals' },
            { city: 'Sanur', type: 'Beachfront rentals' },
            { city: 'Upham Beach Park', type: 'Flat rentals' },
            { city: 'Gulf Shores Public Beach', type: 'Flat rentals' },
            { city: 'Zipolite, Oaxaca', type: 'Pet-friendly rentals' },
            { city: 'Playa Dorada', type: 'Holiday rentals' },
            { city: 'Pupukea', type: 'Flat rentals' },
            { city: 'Sosua Beach', type: 'Holiday rentals' },
            { city: 'Coligny Beach Park', type: 'Holiday rentals' },
            { city: 'Fort Lauderdale Beach', type: 'Apartment rentals' },
            { city: 'Virginia Beach Oceanfront', type: 'Pet-friendly rentals' },
            { city: 'Jomtien Beach', type: 'Beachfront rentals' },
            { city: 'Hiriketiya Beach', type: 'Holiday rentals' },
            { city: 'Waikiki Beach', type: 'Flat rentals' },
            { city: 'Playa Cocles', type: 'Monthly Rentals' },
            { city: 'Negril Seven Mile Beach', type: 'Flat rentals' },
            { city: 'Jamaica Beach', type: 'House rentals' },
            { city: 'Patong Beach', type: 'Apartment rentals' },
            { city: 'Punta Rucia', type: 'Villa rentals' },
            { city: 'Pipa Beach', type: 'Monthly Rentals' },
            { city: 'Galveston Beach', type: 'Flat rentals' },
            { city: 'Hanalei Bay', type: 'Holiday rentals' },
            { city: 'Flamenco Beach', type: 'Beachfront rentals' },
            { city: 'Buyé Beach', type: 'Beachfront rentals' },
            { city: 'Luquillo Beach', type: 'Monthly Rentals' },
            { city: 'Rosarito Beach', type: 'House rentals' },
            { city: 'Bradley Beach', type: 'House rentals' },
            { city: 'Seaside Beach Oregon', type: 'Holiday rentals' },
            { city: 'Bonita Beach', type: 'Flat rentals' },
            { city: 'Alki Beach', type: 'Holiday rentals' },
            { city: 'Poipu Beach', type: 'House rentals' },
            { city: 'Cable Beach', type: 'Holiday rentals' },
            { city: 'Galveston Island', type: 'Apartment rentals' },
            { city: 'Kaanapali Beach', type: 'Flat rentals' },
            { city: 'Sanibel Island', type: 'Beachfront rentals' },
            { city: 'La Jolla Shores Beach', type: 'Pet-friendly rentals' },
            { city: 'Bavaro Beach', type: 'Beachfront rentals' },
            { city: 'Playa Bonita', type: 'Villa rentals' },
            { city: 'Kamala Beach', type: 'Pet-friendly rentals' },
            { city: 'Kailua Beach', type: 'Monthly Rentals' },
            { city: 'Copacabana Beach', type: 'Holiday rentals' },
            { city: 'Grand Anse Beach', type: 'Pet-friendly rentals' },
            { city: 'Grace Bay', type: 'Holiday rentals' },
            { city: 'Sandbridge Beach', type: 'Holiday rentals' },
            { city: 'Coronado Beach', type: 'Rentals with a beach view' },
            { city: 'Isla Verde Beach', type: 'Apartment rentals' },
            { city: 'Manasota Key Beach', type: 'Holiday rentals' },
            { city: 'Acapulco', type: 'Holiday rentals' },
            { city: 'Playa El Tunco', type: 'Pet-friendly rentals' },
            { city: 'Playa El Cuco', type: 'Beachfront rentals' },
            { city: 'Kata Beach', type: 'Villa rentals' },
            { city: 'Playa San Diego', type: 'Holiday rentals' },
            { city: 'Playa Costa de Sol', type: 'Monthly Rentals' },
            { city: 'Praia da Rocha', type: 'Flat rentals' },
            { city: 'Sunrise Beach', type: 'Beachfront rentals' },
            { city: 'Lihue', type: 'Flat rentals' },
            { city: 'Bang Thao Beach', type: 'Beachfront rentals' },
            { city: 'Canggu Beach', type: 'Holiday rentals' },
            { city: 'Conchas Chinas Beach', type: 'House rentals' },
            { city: 'Venice Beach', type: 'Pet-friendly rentals' },
            { city: 'Windy Hill Beach', type: 'Holiday rentals' },
            { city: 'Playa San Pancho', type: 'Rentals with a beach view' },
            { city: 'Blue Bay, Curaçao', type: 'Beachfront rentals' },
            { city: 'Condado Beach', type: 'Beachfront rentals' },
            { city: 'Negril', type: 'Flat rentals' },
            { city: 'Culebra', type: 'House rentals' },
            { city: 'North Beach', type: 'Beachfront rentals' },
            { city: 'Seven Mile Beach', type: 'Flat rentals' },
            { city: 'Marco Beach', type: 'Apartment rentals' },
            { city: 'Gwangalli Beach', type: 'Apartment rentals' },
            { city: 'Seminyak Beach', type: 'Holiday rentals' },
            { city: 'Port Aransas Beach', type: 'House rentals' },
            { city: 'Crystal Beach', type: 'Monthly Rentals' },
            { city: 'Vila Velha', type: 'Apartment rentals' },
            { city: 'Coson', type: 'Holiday rentals' },
            { city: 'Worthing Beach', type: 'Monthly Rentals' },
            { city: 'Siesta Beach', type: 'Flat rentals' },
            { city: 'Playa Mantas', type: 'Holiday rentals' },
            { city: 'Anna Maria', type: 'House rentals' },
            { city: 'San Miguel de Cozumel', type: 'Beachfront rentals' },
            { city: 'South Beach', type: 'Apartment rentals' },
            { city: 'Mambo Beach', type: 'Holiday rentals' },
            { city: 'Crash Boat Beach', type: 'Holiday rentals' },
        ],
        'Mountains': [
            { city: 'Apache Junction', type: 'Pet-friendly rentals' },
            { city: 'Reno', type: 'House rentals' },
            { city: 'Glendale', type: 'Pet-friendly rentals' },
            { city: 'Roseville', type: 'House rentals' },
            { city: 'Pigeon Forge', type: 'Cabin rentals' },
            { city: 'Fullerton', type: 'Holiday rentals' },
            { city: 'Boulder', type: 'Cabin rentals' },
            { city: 'Sunnyvale', type: 'Monthly Rentals' },
            { city: 'Carson City', type: 'Holiday rentals' },
            { city: 'Durango', type: 'Cabin rentals' },
            { city: 'Ogden', type: 'Cabin rentals' },
            { city: 'Mont-Tremblant', type: 'Cabin rentals' },
            { city: 'St. Moritz', type: 'Apartment rentals' },
            { city: 'Fredericksburg', type: 'Monthly Rentals' },
            { city: 'Mesa', type: 'Apartment rentals' },
            { city: 'Brevard', type: 'Cabin rentals' },
            { city: 'Sisters', type: 'Holiday rentals' },
            // Expanded items from image
            { city: 'Cody', type: 'Pet-friendly rentals' },
            { city: 'Red Lodge', type: 'Flat rentals' },
            { city: 'Whitefish', type: 'Holiday rentals' },
            { city: 'Waynesville', type: 'House rentals' },
            { city: 'Tucson', type: 'Villa rentals' },
            { city: 'Idaho Springs', type: 'House rentals' },
            { city: 'Rio Rancho', type: 'Holiday rentals' },
            { city: 'Billings', type: 'Cabin rentals' },
            { city: 'Oslo', type: 'Flat rentals' },
            { city: 'Cheyenne', type: 'Monthly Rentals' },
            { city: 'Palo Alto', type: 'Villa rentals' },
            { city: 'Fayetteville', type: 'Monthly Rentals' },
            { city: 'Alpharetta', type: 'Monthly Rentals' },
            { city: 'Guatemala City', type: 'Monthly Rentals' },
            { city: 'Williams', type: 'Holiday rentals' },
            { city: 'McCall', type: 'House rentals' },
            { city: 'Harrisonburg', type: 'Pet-friendly rentals' },
            { city: 'Buckeye', type: 'House rentals' },
            { city: 'Bristol', type: 'Pet-friendly rentals' },
            { city: 'Cedar City', type: 'Pet-friendly rentals' },
            { city: 'Ironwood', type: 'Pet-friendly rentals' },
            { city: 'El Paso', type: 'Pet-friendly rentals' },
            { city: 'Scranton', type: 'Holiday rentals' },
            { city: 'San Carlos de Bariloche', type: 'Pet-friendly rentals' },
            { city: 'Visalia', type: 'Apartment rentals' },
            { city: 'Glenwood Springs', type: 'Cabin rentals' },
            { city: 'Marbella', type: 'Villa rentals' },
            { city: 'Redding', type: 'Pet-friendly rentals' },
            { city: 'Lawrenceville', type: 'Monthly Rentals' },
            { city: 'Leadville', type: 'Holiday rentals' },
            { city: 'Johnson City', type: 'House rentals' },
            { city: 'San Pedro Garza Garcia', type: 'Holiday rentals' },
            { city: 'Roanoke', type: 'Holiday rentals' },
            { city: 'Zermatt', type: 'Flat rentals' },
            { city: 'Aspen', type: 'Flat rentals' },
            { city: 'Oxford', type: 'Pet-friendly rentals' },
            { city: 'Avondale', type: 'Holiday rentals' },
            { city: 'Kalispell', type: 'Flat rentals' },
            { city: 'Fort Collins', type: 'House rentals' },
            { city: 'Mill Valley', type: 'Holiday rentals' },
            { city: 'Arvada', type: 'Apartment rentals' },
            { city: 'Colorado Springs', type: 'Holiday rentals' },
            { city: 'Bergen', type: 'House rentals' },
            { city: 'Pueblo', type: 'Flat rentals' },
            { city: 'Prescott', type: 'Holiday rentals' },
            { city: 'Durham', type: 'Flat rentals' },
            { city: 'Belgrade', type: 'Holiday rentals' },
            { city: 'Park City', type: 'Villa rentals' },
            { city: 'Gatlinburg', type: 'Cabin rentals' },
            { city: 'Bisbee', type: 'Monthly Rentals' },
            { city: 'Hialeah', type: 'Monthly Rentals' },
            { city: 'Bellingham', type: 'Cabin rentals' },
            { city: 'Helen', type: 'Apartment rentals' },
            { city: 'Flagstaff', type: 'Monthly Rentals' },
            { city: 'Golden', type: 'Cabin rentals' },
            { city: 'Milpitas', type: 'Monthly Rentals' },
            { city: 'Chico', type: 'Monthly Rentals' },
            { city: 'Laramie', type: 'Pet-friendly rentals' },
            { city: 'Ellijay', type: 'House rentals' },
            { city: 'Longmont', type: 'House rentals' },
            { city: 'Juneau', type: 'Holiday rentals' },
            { city: 'Farmington', type: 'Holiday rentals' },
            { city: 'Deadwood', type: 'House rentals' },
            { city: 'San Bernardino', type: 'Pet-friendly rentals' },
            { city: 'Granada', type: 'Hostel rentals' },
            { city: 'Bozeman', type: 'Monthly Rentals' },
            { city: 'Anchorage', type: 'Holiday rentals' },
            { city: 'Winter Haven', type: 'Flat rentals' },
            { city: 'Vancouver', type: 'Pet-friendly rentals' },
            { city: 'Mountain View', type: 'Pet-friendly rentals' },
            { city: 'Rock Hill', type: 'Flat rentals' },
            { city: 'Asheville', type: 'Apartment rentals' },
            { city: 'Sapporo', type: 'Apartment rentals' },
            { city: 'Driggs', type: 'Cabin rentals' },
            { city: 'Fontana', type: 'Holiday rentals' },
            { city: 'Wausau', type: 'Pet-friendly rentals' },
            { city: 'Clovis', type: 'Flat rentals' },
            { city: 'Denver', type: 'Hostel rentals' },
            { city: 'Ozark', type: 'Pet-friendly rentals' },
            { city: 'San Mateo', type: 'Flat rentals' },
            { city: 'Bentonville', type: 'Monthly Rentals' },
            { city: 'Sun Valley', type: 'House rentals' },
        ],
        'Outdoors': [
            { city: 'Lahaina', type: 'Holiday rentals' },
            { city: 'Hurricane', type: 'Holiday rentals' },
            { city: 'Stowe', type: 'House rentals' },
            { city: 'Medford', type: 'Cabin rentals' },
            { city: 'Chamonix', type: 'Cabin rentals' },
            { city: 'Kihei', type: 'Apartment rentals' },
            { city: 'Albufeira', type: 'Apartment rentals' },
            { city: 'Morro Bay', type: 'Cabin rentals' },
            { city: 'Bradenton Beach', type: 'Holiday rentals' },
            { city: 'Key Colony Beach', type: 'Flat rentals' },
            { city: 'Osage Beach', type: 'Flat rentals' },
            { city: 'Quepos', type: 'House rentals' },
            // Expanded items from image
            { city: 'Joshua Tree', type: 'Villa rentals' },
            { city: 'Telluride', type: 'House rentals' },
            { city: 'Punta de Mita', type: 'Beachfront rentals' },
            { city: 'Palm Springs', type: 'Cabin rentals' },
            { city: 'Cape Town', type: 'Cottage rentals' },
            { city: 'Tulsa', type: 'Holiday rentals' },
            { city: 'Carolina', type: 'Apartment rentals' },
            { city: 'Tarpon Springs', type: 'Cottage rentals' },
            { city: 'Key Largo', type: 'House rentals' },
            { city: 'Naxos', type: 'Apartment rentals' },
            { city: 'Phoenix', type: 'House rentals' },
            { city: 'Dana Point', type: 'Beachfront rentals' },
            { city: 'Kanab', type: 'Holiday rentals' },
            { city: 'Uvita', type: 'Flat rentals' },
            { city: 'Tacoma', type: 'Apartment rentals' },
            { city: 'Grindelwald', type: 'Flat rentals' },
            { city: 'Falmouth', type: 'Beachfront rentals' },
            { city: 'Santa Marta', type: 'Holiday rentals' },
            { city: 'Scottsdale', type: 'Holiday rentals' },
            { city: 'Highlands', type: 'Beachfront rentals' },
            { city: 'Wrightsville Beach', type: 'Apartment rentals' },
            { city: 'Ruidoso', type: 'Holiday rentals' },
            { city: 'Bonita Springs', type: 'Cottage rentals' },
            { city: 'Boise', type: 'Apartment rentals' },
            { city: 'Juan Dolio', type: 'Holiday rentals' },
            { city: 'Seward', type: 'Flat rentals' },
            { city: 'Trinidad', type: 'Cabin rentals' },
            { city: 'Luquillo', type: 'Holiday rentals' },
            { city: 'Mammoth Lakes', type: 'House rentals' },
            { city: 'Spring Hill', type: 'Holiday rentals' },
            { city: 'Page', type: 'Flat rentals' },
            { city: 'Duluth', type: 'Flat rentals' },
            { city: 'Astoria', type: 'Holiday rentals' },
            { city: 'Fajardo', type: 'Beachfront rentals' },
            { city: 'Surrey', type: 'Beachfront rentals' },
            { city: 'Big Bear Lake', type: 'Apartment rentals' },
            { city: 'Rosarito', type: 'Apartment rentals' },
            { city: 'Marco Island', type: 'Apartment rentals' },
            { city: 'Lauterbrunnen', type: 'Holiday rentals' },
            { city: 'Laguna Beach', type: 'Rentals with a beach view' },
            { city: 'Hunter Mountain', type: 'Holiday rentals' },
            { city: 'Greensboro', type: 'Flat rentals' },
            { city: 'Leavenworth', type: 'Flat rentals' },
            { city: 'Kailua', type: 'Beachfront rentals' },
            { city: 'Crystal River', type: 'House rentals' },
            { city: 'Akumal', type: 'Apartment rentals' },
            { city: 'Tahoe City', type: 'Beachfront rentals' },
            { city: 'Corvallis', type: 'House rentals' },
            { city: 'Berkeley', type: 'Holiday rentals' },
            { city: 'Moab', type: 'Holiday rentals' },
            { city: 'Boca Raton', type: 'Holiday rentals' },
            { city: 'Virginia Beach', type: 'House rentals' },
            { city: 'Jacksonville', type: 'Holiday rentals' },
            { city: 'Copper Mountain', type: 'Apartment rentals' },
            { city: 'Annecy', type: 'Apartment rentals' },
            { city: 'Taupo', type: 'Holiday rentals' },
            { city: 'Hot Springs', type: 'Villa rentals' },
            { city: 'Paros', type: 'House rentals' },
            { city: 'Revelstoke', type: 'Flat rentals' },
            { city: 'Spokane', type: 'Holiday rentals' },
            { city: 'Bar Harbor', type: 'Holiday rentals' },
            { city: 'Olympia', type: 'House rentals' },
            { city: 'Pacifica', type: 'Villa rentals' },
            { city: 'La Paz', type: 'Villa rentals' },
            { city: 'Punta Cana', type: 'Villa rentals' },
            { city: 'Ventura', type: 'Holiday rentals' },
            { city: 'Kirkland', type: 'Apartment rentals' },
            { city: 'Panama City Beach', type: 'Holiday rentals' },
            { city: 'Big Bear', type: 'House rentals' },
            { city: 'Gold Coast', type: 'Villa rentals' },
            { city: 'Niagara Falls', type: 'Holiday rentals' },
            { city: 'Hilton Head Island', type: 'Apartment rentals' },
            { city: 'Las Terrenas', type: 'Villa rentals' },
            { city: 'Malibu', type: 'House rentals' },
            { city: 'Munising', type: 'Cabin rentals' },
            { city: 'Gainesville', type: 'Holiday rentals' },
            { city: 'Half Moon Bay', type: 'Cottage rentals' },
            { city: 'Ithaca', type: 'House rentals' },
            { city: 'Dahlonega', type: 'Flat rentals' },
            { city: 'Nassau', type: 'Flat rentals' },
            { city: 'Mississauga', type: 'House rentals' },
            { city: 'Bend', type: 'Flat rentals' },
            { city: 'El Nido', type: 'Flat rentals' },
            { city: 'Banff', type: 'Holiday rentals' },
            { city: 'Marathon', type: 'House rentals' },
            { city: 'Austin', type: 'Flat rentals' },
            { city: 'Princeville', type: 'Holiday rentals' },
        ],
        'Things to do': [
            { city: 'Puebla', type: 'Art and culture' },
            { city: 'Mexico City', type: 'Wellness' },
            { city: 'Durham', type: 'Nature and outdoors' },
            { city: 'Apennine Mountains', type: 'Sports activities' },
            { city: 'Honshu', type: 'Food and drink' },
            { city: 'San Juan', type: 'Sightseeing' },
            { city: 'Seine', type: 'Art and culture' },
            { city: 'Paris', type: 'Nature and outdoors' },
            { city: 'Tokyo', type: 'Art and culture' },
            { city: 'Tama River', type: 'Sightseeing' },
            { city: 'Rome', type: 'Sports activities' },
            { city: 'Medellin River', type: 'Sightseeing' },
            { city: 'Medellín', type: 'Nature and outdoors' },
            { city: 'Plainview', type: 'Sports activities' },
            { city: 'Juárez', type: 'Things to do' },
            { city: 'Tokyo Bay', type: 'Sports activities' },
            { city: 'Roma Norte', type: 'Things to do' },
            // Expanded items from image
            { city: 'Florence', type: 'Things to do' },
            { city: 'Barcelona', type: 'Food and drink' },
            { city: '1st Arrondissement', type: 'Things to do' },
            { city: 'Channel Islands of California', type: 'Art and culture' },
            { city: 'London', type: 'Sports activities' },
            { city: 'Hudson River', type: 'Entertainment' },
            { city: 'Madrid', type: 'Things to do' },
            { city: 'Manhattan', type: 'Entertainment' },
            { city: 'Panama Canal', type: 'Things to do' },
            { city: 'Canals of Amsterdam', type: 'Tours' },
            { city: 'Shinjuku', type: 'Things to do' },
            { city: 'Port of Barcelona', type: 'Tours' },
            { city: 'Istanbul', type: 'Entertainment' },
            { city: 'Venezia', type: 'Food and drink' },
            { city: 'Seminole', type: 'Entertainment' },
            { city: 'Shibuya', type: 'Sports activities' },
            { city: 'Miami', type: 'Sightseeing' },
            { city: 'Porto', type: 'Things to do' },
            { city: 'Long Island', type: 'Things to do' },
            { city: 'Eixample', type: 'Things to do' },
            { city: 'Los Angeles', type: 'Sightseeing' },
            { city: 'Chao Phraya', type: 'Entertainment' },
            { city: 'Miami Beach', type: 'Art and culture' },
            { city: 'Saronic Islands', type: 'Nature and outdoors' },
            { city: 'Evvoia', type: 'Nature and outdoors' },
            { city: 'Tulum', type: 'Things to do' },
            { city: 'San Francisco', type: 'Sports activities' },
            { city: '16th Arrondissement', type: 'Things to do' },
            { city: 'Xochimilco', type: 'Food and drink' },
            { city: 'Santa Maria Maior', type: 'Tours' },
            { city: 'Centro', type: 'Things to do' },
            { city: 'Puerto Vallarta', type: 'Entertainment' },
            { city: 'New York City', type: 'Things to do' },
            { city: 'Medina', type: 'Things to do' },
            { city: 'Amsterdam', type: 'Things to do' },
            { city: 'Nomos Kykladon', type: 'Nature and outdoors' },
            { city: 'Cythera', type: 'Food and drink' },
            { city: 'East Attica Regional Unit', type: 'Nature and outdoors' },
            { city: 'Athens', type: 'Nature and outdoors' },
            { city: 'Getsemani', type: 'Things to do' },
            { city: 'Palermo', type: 'Things to do' },
            { city: 'City of Westminster', type: 'Entertainment' },
            { city: 'Oaxaca', type: 'Sports activities' },
            { city: 'Stanton', type: 'Entertainment' },
            { city: 'Mississippi River', type: 'Sightseeing' },
            { city: 'Oued Tensift', type: 'Sports activities' },
            { city: 'Arcozelo', type: 'Sports activities' },
            { city: 'Guanabara Bay', type: 'Tours' },
            { city: 'Oahu', type: 'Nature and outdoors' },
            { city: 'Panama City', type: 'Tours' },
            { city: 'Honolulu', type: 'Art and culture' },
            { city: 'Regional Unit of Islands', type: 'Entertainment' },
            { city: 'Kentrikou Tomea Athinon', type: 'Nature and outdoors' },
            { city: 'Centro Madrid', type: 'Things to do' },
            { city: 'Carolina', type: 'Things to do' },
            { city: 'Great Britain', type: 'Food and drink' },
            { city: 'Elgin', type: 'Art and culture' },
            { city: 'Seoul', type: 'Sports activities' },
            { city: 'Thames River', type: 'Tours' },
            { city: 'Queens', type: 'Things to do' },
            { city: 'East River', type: 'Entertainment' },
            { city: 'Francavilla al Mare', type: 'Sightseeing' },
            { city: 'Shinjuku', type: 'Food and drink' },
            { city: 'Regent\'s Canal', type: 'Food and drink' },
            { city: 'Venice', type: 'Sightseeing' },
            { city: 'Hanoi', type: 'Sightseeing' },
            { city: 'San Francisco Peninsula', type: 'Food and drink' },
            { city: '4th Arrondissement', type: 'Things to do' },
            { city: '7th Arrondissement', type: 'Things to do' },
            { city: 'El Poblado', type: 'Things to do' },
            { city: 'Kyoto', type: 'Things to do' },
            { city: 'New Orleans', type: 'Sports activities' },
            { city: 'Cartagena', type: 'Food and drink' },
            { city: 'Kamo River', type: 'Tours' },
            { city: 'Area Metropolitana y Corredor del Hena...', type: 'Food and drink' },
            { city: 'Bangkok', type: 'Sightseeing' },
            { city: 'Ancón', type: 'Sports activities' },
            { city: 'Stadsdeel Centrum', type: 'Things to do' },
            { city: 'Venetian Lagoon', type: 'Sports activities' },
            { city: 'San Diego', type: 'Art and culture' },
            { city: 'Higashiyama Ward', type: 'Things to do' },
            { city: 'Osaka', type: 'Tours' },
        ],
    };

    const footerLinks = [
        {
            title: 'Support',
            links: [
                'Help Centre',
                'Get help with a safety issue',
                'AirCover',
                'Anti-discrimination',
                'Disability support',
                'Cancellation options',
                'Report neighbourhood concern'
            ]
        },
        {
            title: 'Hosting',
            links: [
                'Airbnb your home',
                'Airbnb your experience',
                'Airbnb your service',
                'AirCover for Hosts',
                'Hosting resources',
                'Community forum',
                'Hosting responsibly',
                'Join a free hosting class',
                'Find a co-host',
                'Refer a host'
            ]
        },
        {
            title: 'Airbnb',
            links: [
                'Newsroom',
                '2025 Summer Release',
                'Careers',
                'Investors',
                'Airbnb.org emergency stays'
            ]
        }
    ];

    const getDisplayedItems = () => {
        const items = inspirationData[activeTab] || inspirationData['Popular'];
        if (!isExpanded) {
            return items.slice(0, 17);
        }
        return items;
    };

    const showShowMore = !isExpanded && (inspirationData[activeTab]?.length > 17 || false);

    return (
        <footer className="w-full bg-white border-t border-[#DDDDDD] text-[#222222] font-sans">
            <div className="max-w-[1280px] mx-auto py-12 px-6 md:px-10">
                {/* Inspiration Section */}
                <div className="mb-12 border-b border-[#DDDDDD] pb-12">
                    <h2 className="text-[22px] font-semibold mb-6 text-[#222222]">Inspiration for future getaways</h2>
                    <div className="flex gap-6 border-b border-[#DDDDDD] mb-8 overflow-x-auto hide-scrollbar">
                        {tabs.map((tab) => (
                            <button
                                key={tab}
                                className={`bg-transparent border-none text-sm py-2.5 cursor-pointer font-semibold whitespace-nowrap relative ${activeTab === tab
                                    ? 'text-[#222222] border-b-2 border-[#222222]'
                                    : 'text-[#717171] hover:text-[#222222] hover:underline'
                                    }`}
                                onClick={() => { setActiveTab(tab); setIsExpanded(false); }}
                            >
                                {tab}
                            </button>
                        ))}
                    </div>
                    <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-x-2 gap-y-6">
                        {getDisplayedItems().map((item, index) => (
                            <div key={index} className="flex flex-col cursor-pointer">
                                <span className="text-sm font-semibold text-[#222222]">{item.city}</span>
                                <span className="text-sm text-[#717171]">{item.type}</span>
                            </div>
                        ))}
                        {showShowMore && (
                            <div className="flex flex-col justify-center">
                                <span
                                    className="text-sm font-semibold text-[#222222] flex items-center gap-1 cursor-pointer hover:underline"
                                    onClick={() => setIsExpanded(true)}
                                >
                                    Show more <ChevronDown size={16} />
                                </span>
                            </div>
                        )}
                    </div>
                </div>

                {/* Footer Links Section */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pb-12 border-b border-[#DDDDDD]">
                    {footerLinks.map((column, index) => (
                        <FooterColumn key={index} title={column.title} links={column.links} />
                    ))}
                </div>

                {/* Bottom Bar */}
                <div className="flex flex-col-reverse md:flex-row justify-between items-center pt-6 text-sm text-[#222222]">
                    <div className="flex gap-2 mt-8 md:mt-5">
                        <span className="cursor-pointer">© 2026 Airbnb, Inc.</span>
                        <span className="cursor-pointer">·</span>
                        <a href="#" className="text-[#222222] no-underline hover:underline cursor-pointer">Privacy</a>
                        <span className="cursor-pointer">·</span>
                        <a href="#" className="text-[#222222] no-underline hover:underline cursor-pointer">Terms</a>
                        <span className="cursor-pointer">·</span>
                        <a href="#" className="text-[#222222] no-underline hover:underline cursor-pointer">Company details</a>
                    </div>

                    <div className="flex gap-6 items-center font-semibold text-[#222222]">
                        <div className="flex items-center gap-2 cursor-pointer hover:underline">
                            <Globe size={16} />
                            <span>English (IN)</span>
                        </div>
                        <div className="flex items-center gap-2 cursor-pointer hover:underline">
                            <span>₹ INR</span>
                        </div>
                        <div className="flex gap-4">
                            <a href='#' className="hover:text-gray-600"><Facebook size={18} /></a>
                            <a href='#' className="hover:text-gray-600"><Twitter size={18} /></a>
                            <a href='#' className="hover:text-gray-600"><Instagram size={18} /></a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    );
};

export default Footer;
